### ISSUE TITLE
Combine state active and minimize app

### ISSUE THREAD

**Issue by varlesh** [psifidotos/nowdock-plasmoid#10]
I think, maybe better combine **touch** and **line** on dock - this variant reduce vertical size on plasma panel.
Original
![screenshot_20160815_164550](https://cloud.githubusercontent.com/assets/8083855/17666340/837b9996-6308-11e6-89c8-83f71d67aae8.png)

Combined
![fix](https://cloud.githubusercontent.com/assets/8083855/17666349/890fe8b2-6308-11e6-9cb8-87705dc60210.png)

**Comment by psifidotos** [comment]
how would you show for Active window that there are also other windows ?

**Comment by varlesh** [comment]
**Active** window have **line**, **minimize/background** app have **dot**

**Comment by psifidotos** [comment]
I mean that if there are two or more dolphin windows then two dots appear...
with the current implementation a user can see also if a dolpin window is active but also if there is a second dolphin window which is minimized or shown...

**Comment by varlesh** [comment]
With two dots this look good too, because active only one window. I mean need move dots-area up and combine with line (minimize/background apps) - this reduce size panel.
For example, panel with dock 32px:
![image](https://cloud.githubusercontent.com/assets/8083855/17676083/5dc98230-6335-11e6-99bc-77486ddfbe07.png)
dot-area and line-area - It takes a lot of space

**Comment by varlesh** [comment]
Or maybe another way - use only dots, line-area remove.
colorize dot - active window
not colorize dot - background window
PS: Sorry my English ))

**Comment by psifidotos** [comment]
I suppose you want to gain that space below the icon... :)

can you make a screenshot how would it look if the dots went next to the line?

eg. a blue line and next to it at its end a lightgrey dot and and light dark dot...

That it would mean for example I have a dolphin active, a dolphin minimized and a dolphin shown which is not active

**Comment by varlesh** [comment]
Also you can use elements from tasks widget for this. Or add (draw) manually triangle  on line
run one dolphin:
![image](https://cloud.githubusercontent.com/assets/8083855/17676430/2e557c1e-6337-11e6-89e5-bcb4f339c5fe.png)
run two dolphin:
![image](https://cloud.githubusercontent.com/assets/8083855/17676451/4bf2e52c-6337-11e6-8b20-71f4e05d6c1c.png)

**Comment by varlesh** [comment]
ONE AREA:
dot - background/minimize window
two dots - two window on background
line - active window
line with triangle (if active one window) - ruining two window

**Comment by varlesh** [comment]
![dots](https://cloud.githubusercontent.com/assets/8083855/17676939/4f013a78-6339-11e6-9d3a-47c88d75cf03.png)

**Comment by psifidotos** [comment]
varlesh have you tried the three colorings,  I introduced yesterday? in order to play with?
blue,  active
light - grey, isMinimized
dark - grey, isShown
it could give you even more inspiration..

it is in the master branch...

**Comment by varlesh** [comment]
"blue, active
light - grey, isMinimized
dark - grey, isShown"
I don't know how this looking with different plasma themes. Colors can merge?
I want only ONE area, because this save space on panel

**Comment by psifidotos** [comment]
go to the configuration dialog, and check "Different colors for window states",

after that open three Dolphin windows and see what happens...

minimize also one and see what changes in coloring...

Yes in one area I can have two different colors at the same time, and I could have three different also in some cases...

**Comment by varlesh** [comment]
Yes, i seen this. Now dock have colors and line. Maybe line not needed anymore?
![dots2](https://cloud.githubusercontent.com/assets/8083855/17677727/cb57a97e-633c-11e6-8665-d487ae826905.png)
1 - active one window
2 - inactive one window
3  - active and inactive windows
4 - inactive windows

**Comment by psifidotos** [comment]
I want the active to be shown immediately that is why I want the line and because is a Plasma standard these days... Everywhere there are lines to show focus...

![image](https://cloud.githubusercontent.com/assets/2216474/17677846/486d797a-633d-11e6-8f69-6a2be0efea67.png)

the light grey is for a window that is minimized

**Comment by varlesh** [comment]
Why you don't want use only dots with colors? It's original and looks fine (i think). Also this variant save space, because line will be removed and dots area will be shifted.
You developer - you right! It's only my desire :)

**Comment by varlesh** [comment]
I know, you want use dock with transparent plasma theme, but this not universal for other themes. Available very more beautiful other themes - Caledonia, Breeze, Helium and etc.. this themes not have full transparent panel.

**Comment by varlesh** [comment]
i want only reduce panel size, because panel look very big with line and dots:
![reduce](https://cloud.githubusercontent.com/assets/8083855/17678447/cc7c3bd2-633f-11e6-8efd-cd54fd1cc774.png)

**Comment by psifidotos** [comment]
I want the line for active :-) but I also want the reduce the space :-)

I am thinking the two dots if there is no active and line and dot if it is active it would do it...

I am not against other themes... I llike Breeze and Caledonia a lot!!! I am trying to convince the designers that a user could use their theme but choose that one panel would like to be fully  transparent... It can be done and I am hoping for a response in that...

If the panel is not transparent... The zoom effect loses its magic....

If someone comes with an answer in this... For example a Breeze Dark theme that the right panel is fully tranparent then I could mimic a panel beneath my icons and the zoom effect visual would grow outside the panel...

So I want the user to decide what background wants for its icons but also the zoom effect to keep its magic....

Either way the line is a very important aspect to lose it...
I suppose you dont use the zoom effect but I like a lot... :)

**Comment by varlesh** [comment]
Yes, i'm don't use zoom because panel very big ))

**Comment by varlesh** [comment]
if this variant?
![dots3](https://cloud.githubusercontent.com/assets/8083855/17678778/47b33854-6341-11e6-87af-a41c84fccca0.png)
1 - active one window
2 - inactive one window
3 - active and inactive windows
4 - inactive windows

**Comment by varlesh** [comment]
or
![dots4](https://cloud.githubusercontent.com/assets/8083855/17678900/c1bcef0a-6341-11e6-8df8-0ec8e434c84b.png)

**Comment by varlesh** [comment]
or
![dots5](https://cloud.githubusercontent.com/assets/8083855/17678932/ee119ee8-6341-11e6-992c-23aa619a7159.png)

**Comment by varlesh** [comment]
If you like lines, maybe better use only lines?
![lines](https://cloud.githubusercontent.com/assets/8083855/17679191/01095eb8-6343-11e6-980a-dfe0837198c8.png)
PS: I like this variant

**Comment by psifidotos** [comment]
what do you think?

![image](https://cloud.githubusercontent.com/assets/2216474/17680583/9335e2a6-6349-11e6-80cc-41be1746348e.png)

![image](https://cloud.githubusercontent.com/assets/2216474/17680610/af2c2100-6349-11e6-9189-ed4416d13692.png)

**Comment by varlesh** [comment]
On 1 screen - maybe better use two lines (for dolphin)? Because dot shifted to the right and not good looking.

**Comment by varlesh** [comment]
![333](https://cloud.githubusercontent.com/assets/8083855/17680911/488ece3c-634b-11e6-889c-7560c3c23430.png)

**Comment by psifidotos** [comment]
I am not sure that it isnt looking good for example your screenshot with two separate lines
is too heavy in the eye..

**Comment by varlesh** [comment]
Maybe this variant?
![image](https://cloud.githubusercontent.com/assets/8083855/17681164/a8fb8d9a-634c-11e6-8e4d-8a19ea6450b4.png)

**Comment by varlesh** [comment]
one active window - line
others - dots

**Comment by varlesh** [comment]
active window - one blue line
inactive window - white dot
minimize window - grey dot
active window  & inactive window - blue dot & white dot 
active window & minimize window - blue dot & grey dot
and etc...

**Comment by psifidotos** [comment]
in branch mergeStates I have just uploaded... play around a bit with it.. and we will see... :)

**Comment by varlesh** [comment]
ok

**Comment by varlesh** [comment]
looks cool... i see, you shifted state area - it's good :) 

But i think, if run one app twice - will be better use blue dot and grey/white. Because line with dot not good looking with little size.
For example 22px:
![image](https://cloud.githubusercontent.com/assets/8083855/17681770/5771dea8-6350-11e6-96ed-75174cf3e38a.png)

**Comment by psifidotos** [comment]
Let's play with it.. and we 'll see... currently the size of the dots and the line is static... If I remember correctly it is 6px, this doesnt have any sense for sizes as low as 22px... 

1) this can be changed... The size of the size can take into account the size of the icon ...
2) if there is a debate about how it should appear when there are "two dolphins" and one is active... we'll see.. I except also the Plasma VDG for their ideas at some point...
But if this ends at a debate I can always make as default for the most wanted choice and the other to can be enabled from the configuration dialog... just like the 3 different colors... for some people it may be too much... they could prefer just one color to rule them all....

thanks a lot @varlesh.... great work today !!! :)

**Comment by varlesh** [comment]
Yes, you right! Many people - many variants... It's only my say. You developer - you main!!!
Nevertheless dock look now very cool. It's your merit, i'm only help you :) 
Thx for your work

**Comment by varlesh** [comment]
Closed, because state-area shifted and combined

**Comment by psifidotos** [comment]
I have just updated this...

"on active window no dots" - this is the default

but the user can choose from the settings to change this in order to see a dot with active window if he wants to....

regards,
michail

**Comment by varlesh** [comment]
very cool 👍 thx)

**Comment by psifidotos** [comment]
@varlesh  this is what I had in mind...
I dont like transparent themes so much... I prefer dark good designed themes most.
 I wanted just the choice the panel in which the Now Dock will be placed to be transparent...
This is Breeze Dark Theme and only the panel in which the Dow Dock is placed is transparent...

![image](https://cloud.githubusercontent.com/assets/2216474/17729447/f6eb9b28-646c-11e6-8c28-c9bda6ac3aec.png)

**Comment by psifidotos** [comment]
And this is Papirus theme with Now Dock living outside its dock!! :)
I hope you see this @varlesh :-)

![image](https://cloud.githubusercontent.com/assets/2216474/17805566/c2032e42-6608-11e6-9819-c9d1f3a2ed84.png)
