### ISSUE TITLE
Hard to see window states

### ISSUE THREAD

**Issue by Steinhagen** [psifidotos/nowdock-plasmoid#11]
Different colors for windows state should take in consideration plasma's theme.
Using 'Breeze' theme with 'Plasma theme panel' and 'Different color for window states' will result in unseenable dots.

**Comment by psifidotos** [comment]
I know... What I dont know is what colors to use from the theme...

there are two states that I dont know with what colors from the theme to link with...
WIndow is Shown
and
Window is Minimized (the brightness or contrast for this it should be higher for the window is shown case), when a user looks the shown window are on its screen but the minimized because they are not shown they should have a more recognizable visual...

any ideas?

**Comment by Steinhagen** [comment]
> any ideas?

Not right now.

The way I see it, the modification done for this ticket should probably also address the following accessibility issue: Will a color blind person have trouble distinguishing the different window states?

**Comment by Steinhagen** [comment]
I've just got the chance to try the new patches and indeed seems to somewhat fix the problem. My only complaint is that the active windows are not clearly seen using Breeze (not Breeze Dark).

While I'm at this topic, I got a question. Why there is a need for 3 different colors in the dock? This only make the color choosing hard for custom themes. Since there are 2 different window status icons, underscore for the window with the focus and the dot for all other windows, why not limit the colors palette only to 2? In our case:
Breeze Dark: Grey for minimized windows and blue for the rest.
Breeze: Black for minimized windows and blue for the rest.

**Comment by psifidotos** [comment]
You 've got a point in this...

I hadnt thought it this way... Three states colors for shown, minimized, active looked very interesting in the begin... But the fact that we use line and dots probably does not make necessary the third color for shown windows...

Let me play with it ...

thank you for the idea... :+1:

If visually looks ok it will also make the code simpler...

**Comment by psifidotos** [comment]
I have uploaded in scratch a change for this... I dropped the third color for shown windows...

**Comment by Steinhagen** [comment]
I've just got the chance to test the new patch. It looks great!
I think that this ticket should be closed as soon as the scratch branch will be merged on master.

**Comment by psifidotos** [comment]
Nice !! :-) when the scratch codepage goes to master this is going to be closed automatically..
