### ISSUE TITLE
The ability to add places to the dock

### ISSUE THREAD

**Issue by Steinhagen** [psifidotos/nowdock-plasmoid#13]
A possible improvement for Now Dock would be the ability to add certain unremovable places to it (like Trash or even the KDE's Application Dashboard). A checkbox (or something similar) could be added to the dock's option menu to display (or hide) that application/location.

**Comment by psifidotos** [comment]
this is a final target... :-) I dont know when this could be possible...

It looks like a panel functionality,  but a panel that behaves to its plasmoids according to the now dock way...

It looks advance but we will see... :)

**Comment by psifidotos** [comment]
I am starting to working this in my head... And it doesnt look so frightening...
Can you expain me what do you mean by unremovable places? Dont you mean folders?

about the application addition, removal... This is already possible through launchers...
Drop any application icon on the plasmoid and it is going to be added as a permanent launcher...

**Comment by Steinhagen** [comment]
> Can you expain me what do you mean by unremovable places? Dont you mean folders?

Yes. Originally I was thinking of the trash:/ place, but that can be added as an applet as well.

**Comment by psifidotos** [comment]
The only I can think for this, is at some point the Now Dock to support applet addition... e.g. the clock, the trash, the dashboard launcher etc...

For this to happen the only solution I can think of is a Now Dock Panel... One which is going to behave to the apllets the way the Now Dock plasmoid does... Supporting the zoom animation for the applets... order them according to the Now Dock plasmoid etc....

I dont know how difficult can this be... but it would be fantastic if it could be implemented...

**Comment by psifidotos** [comment]
Duplicate for #16
