### ISSUE TITLE
Unability to move and remove from desktop

### ISSUE THREAD

**Issue by davorb** [psifidotos/nowdock-plasmoid#14]
I added this as a widget to the desktop, but now I find myself with two problems:
1. I am unable to move it from it's initial position.
2. I am unable to remove it from the desktop.

**Comment by psifidotos** [comment]
I hope you are ok now...  If you need help, ping me !!

**Comment by davorb** [comment]
Yeah, sorry. This was an issue with KDE and I managed to fix it.

Thanks for your hard work on this. :+1:

**Comment by psifidotos** [comment]
no worries !!! :+1:
