### ISSUE TITLE
show dock when full-screen?

### ISSUE THREAD

**Issue by RussH** [psifidotos/nowdock-plasmoid#15]
Hi, this is great - only thing I'm missing (from Plank!) now is when there's a maximised window, I'd like to hold the mouse-pointer at the bottom of the screen for a few seconds, and the dock would appear. I assume this is tricky using a plasmoid?

**Comment by psifidotos** [comment]
hello,

how do you use it ? in a panel or in desktop?

if you put the plasmoid in a panel then there are cases that the plasmoid shows itself even if it is under fullscreen windows... for example when a window demands attention, the plasmoid shows itself for 5 secs. For example open a dolphin window and before the new dolphin window is created click another fullscreen window, when the dolphin window is created you will not see the dolphin window but the Now Dock plasmoid will show you a beautiful animation for 5 secs.

**Comment by RussH** [comment]
ahh thank you I was using it standalone on the desktop. I will try a panel!

**Comment by psifidotos** [comment]
Ok! :-)
I hope you succeed in this!

the main way to use in a panel...
1. Add an empty panel in your systems, right click on the desktop -> Add Panel -> Empty Panel

and after that add the Now Dock Plasmoid in that panel...
