### ISSUE TITLE
Implementation as a panel

### ISSUE THREAD

**Issue by Steinhagen** [psifidotos/nowdock-plasmoid#16]
This is just a suggestion for a thing that bothered be for quite a while.

For now, to have implement Now Dock you need a transparent panel that need to be created using a separate script (unless you know what you're doing). Wouldn't it be possible to implement Now Dock as a 'Panel' option?
- Right click on the desktop -> Add Panel -> Now Dock

The way I see it, the desired behaviour should be similar to that of:
- Right click on the desktop -> Add Panel -> System tray empty

The code for that is already implemented and can be taken as a reference. Different from the 'System tray empty option', the dock should have a transparent panel.

This ticket should be taken as an 'enhancement' proposal. I would like to hear your idea about this and maybe potential + / - that I haven't thinked about.

**Comment by psifidotos** [comment]
To make the plasmoid to a panel like "Right click on the Desktop -> Add Panel -> Now Dock" is not that hard... I almost have already implemented but... there arent many benefits.. 

I am going to describe here my adventure for Now Dock as a panel :) and in the end my thoughts concerning the implementation...

Currently making the Now Dock a panel directly has some issues which are... 
*) the configuration options of Now Dock plasmoid are lost
*) the panel can not be made transparent by the code, tranparent panel still needs a theme that supports that transparency for that panel

as I see it the only benefit currently is that the user doesnt have to add the Now Dock Plasmoid into the panel by himself, the Now Dock panel could do that for him but the transparency is not yet ready...

From the Plasma developers the responses are positive around the transparency... A plasmoid will be able to set a panel transparent without changing anything from the theme but this is not going to land before Plasma 5.9 or 5.10

So what are the benefits now? I dont see plently actually... :-)

For the future... I am not imagining a Now Dock Panel which shows the Now Dock Plasmoid and its use would stop there...

I am thinking if this Now Dock Panel is possible to be a panel that you can add widgets in it... 

When the user adds it by default the Now Dock plasmoid appears in it, the user doesnt have to add it...
After that I would like to try to add widgets surrounding the Now Dock plasmoid. For example someone wants #13 add places, or add a clock, or add a launcher..

I will experiment in some point to add widgets in the panel and try to make them behave just like the Now Dock windows icons... zoom effect, clicking etc... But I dont know if I am going to be succesful in this... :)

**Comment by Steinhagen** [comment]
I'm kindly impressed of your plan of action. I look forward to future improvements!
With that being said, I believe that this issue can be closed.

**Comment by psifidotos** [comment]
I played a little with this today and I have a concept of proof for this !!!! :-)  but it needs of course a lot of fine tuning, take functionality from the plasmoid and use it also to the panel and make the Now Dock Panel and the Now Dock plasmoid to behave correctly to each other... :-) but the clock grows... places grow etc... and the Now Dock plasmoid provide to the panel configuration settings...

I would say to leave it open for now... Let's have it as a discussion place until the Now Dock Panel arrives... I dont feel it's that far actually, maybe one or two months... ;-)

**Comment by psifidotos** [comment]
There is a Now Dock Panel :), so lets try to make it better...

[Now Dock Panel](https://github.com/psifidotos/nowdock-panel)
