### ISSUE TITLE
Windows Previews

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/nowdock-plasmoid#18]
When the user hovers a task a WindowPreview window is shown to him...

This a feature that could be implemented but I dont know how many users need this...

**Comment by kupiqu** [comment]
I would like to see this feature implemented...

Thanks for the good work!

**Comment by psifidotos** [comment]
hovering is enabled in **master** thourgh the configuration dialog

**Comment by kupiqu** [comment]
Oops my bad, I misunderstood the feature. I thought it was about the small preview of the window that emerges by the side of the hovering, not the highlight of the window itself wherever it is. Could you please implement that other feature, which actually is the one I use?

May I need to open another issue, instead?

**Comment by AndydeCleyre** [comment]
Yes, please re-open, window previews as the icon-only task switcher offers would be nice, and is what this issue's description seems to describe.

**Comment by psifidotos** [comment]
Ohhhhh....

**Comment by SteveKej** [comment]
Just mentioning that I also would like previews that kupiqu and AndydeCleyre described.

**Comment by AndydeCleyre** [comment]
This would make it easy to select the correct window when multiple windows are open for an app.

Although plank doesn't offer previews, it does list the windows in the context menu.

**Comment by psifidotos** [comment]
this is merged in **master**
