### ISSUE TITLE
"Per-activity pinned tasks" through Activities infrastructure

### ISSUE THREAD

**Issue by alexjp** [psifidotos/nowdock-plasmoid#25]
Hi,

Sorry, yet another issue :)

I say this todo in plasma : https://phabricator.kde.org/T2025

Its "Per-activity pinned tasks".

This seems similar to the newDock's launchers per activity.

What do you think ?

**Comment by psifidotos** [comment]
I think is describing the same thing...
The plasma developers are mentioning a try for this to be done through Activities library...

**Comment by psifidotos** [comment]
I supposed you are proposing to use the Activities mechanish in order to store launchers per Activity, right?

**Comment by alexjp** [comment]
No, not at all !!!

That is up to you. Just wanted to share if there is duplicated efforts.

The way you did it, seems much simpler and faster. Using Activities mechanism is going to be tricky, because you can link alot of things to the activity, not just launchers.

**Comment by psifidotos** [comment]
so then, this is the same problem but different approaches...

plasma developers would like definitely this to go into Activities, this is my guess... :)

**Comment by psifidotos** [comment]
I think this is not needed as a reference for now...
