### ISSUE TITLE
Just Checking -- impossible to "intellihide," right?

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/nowdock-plasmoid#27]
Hi,

Thanks for this project!

I believe it's impossible in Plasma, but could this dock offer something like Plank's intellihide? That is, hide if the active window obscures the dock, but don't hide if the active window does not obscure the dock?

I would need this in order to access the dock at all, because in Plasma, if you set a panel to autohide while you have desktop-edge switching turned on, the panel becomes completely inaccessible (yes, even when there are no desktops at that edge).

Sadly, without this I literally cannot use this plasmoid.

**Comment by psifidotos** [comment]
"Intellihide" or "Below Active" as I call it must be implemented inside KWin in order to work...

Currently the best solution for me was to add the plasmoid in a regular panel and set panel to "Windows can cover it".... Also we now have a Now Dock Panel in which you can add the plasmoid and this panels sets the sizes correctly and animates also a lot of the different applets in it...

**Comment by AndydeCleyre** [comment]
On Plasma 5.7.4, "Windows can cover" mode means, at least with desktop edge switching on, that you have to click on the panel to raise it. But if it's covered by windows, I can't click on it. So that seems not so useful.

I don't see Now Dock Panel in the plasmoid downloader, where can I learn more about that, if it might help?

**Comment by AndydeCleyre** [comment]
On Plasma 5.7.4, "Windows can cover" mode means, at least with desktop edge switching on, that you have to click on the panel to raise it. But if it's covered by windows, I can't click on it. So that seems not so useful.

I don't see Now Dock Panel in the plasmoid downloader, where can I learn more about that, if it might help?

**Comment by AndydeCleyre** [comment]
On Plasma 5.7.4, "Windows can cover" mode means, at least with desktop edge switching on, that you have to click on the panel to raise it. But if it's covered by windows, I can't click on it. So that seems not useful at all.

I don't see Now Dock Panel in the plasmoid downloader, where can I learn more about that, if it might help?

**Comment by psifidotos** [comment]
> "Windows can cover" mode means, at least with desktop edge switching on, that you have to click on the panel to raise it.

This isnt correct... You just have to have the edge of the panel free in desktop edge switching...  In my system i have left centered panel and I can also use the bottom left corner for minimizing all windows and my top right corner for presenting all windows ... I use Plasma 5.7.4

**Comment by psifidotos** [comment]
> I don't see Now Dock Panel in the plasmoid downloader, where can I learn more about that, if it might help?

I havent made a release yet because I wanna first to test it... For several days I dont have any issues... This is my main panel...
https://github.com/psifidotos/nowdock-panel/

**Comment by psifidotos** [comment]
Important!! For the best experience with Now Dock Panel **master** branch, install also Now Dock Plasmoid from the **master** branch

**Comment by AndydeCleyre** [comment]
> You just have to have the edge of the panel free in desktop edge switching

What does this mean? With desktop edge switching turned on, it is not possible to choose edges, it's all or nothing.

**Comment by AndydeCleyre** [comment]
Ah, actually, I see that this problem with "Windows can cover" is only a problem with _maximized_ windows.

**Comment by psifidotos** [comment]
> "Windows can cover" is only a problem with maximized windows.

not for me... the only case that the panel is not shown when I move my mouse to its edge is when a window has been set "Always On Top"

**Comment by AndydeCleyre** [comment]
And you have enabled desktop edge switching for the test?

**Comment by AndydeCleyre** [comment]
I've reported this on the [kde tracker](https://bugs.kde.org/show_bug.cgi?id=368362).

**Comment by psifidotos** [comment]
Ohhhhh, sorry!!!
"Desktop Switching" !!! I dont use it at all!! I use the Pager for changing Desktops or Activities in my case...

**Comment by psifidotos** [comment]
move to panel issues....
https://github.com/psifidotos/nowdock-panel/issues/6

Reported upstream...
https://bugs.kde.org/show_bug.cgi?id=368385
