### ISSUE TITLE
Window Preview minimized window Clipping

### ISSUE THREAD

**Issue by alexjp** [psifidotos/nowdock-plasmoid#28]
Hi,

You seem to be nailing every upstream bug in plasma and kwin :) I am actually getting discouraged in KDE/Plasma.

With windows minimized, with window preview, windows leave "clipping".

See screenshot -> http://imgur.com/a/CX6wM

That is two windows minimized : dolphin and konsole. when cycling between them, the previous hovered window leaves the borders on screen.

Yeah ... may mark this upstream right away, but just so you know :)

Thanks for the dock, I am really happy with it on the current configuration I have.

PS: reported -> https://bugs.kde.org/show_bug.cgi?id=368495

**Comment by psifidotos** [comment]
> You seem to be nailing every upstream bug in plasma and kwin :)

I know... :-) but this is also a way to move things forward...
Trying to support something like Now Dock officially from plasma technologies shows weaknesses that previous were not that important or many users didnt see them...

By creating user momentum and new user needs, I believe the developers will be also motivated to new directions... In the end all developers want their children/programs to run smoothly and correctly... etc.

So, I have faith... !! :)
- report upstream
- show the users needs
- and in many cases developers will follow

even a simple thing like reporting a bug, show to the developer that its software is used !!! :)
and this is important...

**Comment by psifidotos** [comment]
I just thought something...

I will create a new issue, one that everyone will be able to show its Now Docks configurations!!! In order to exchange ideas and create a small community!!! :)

**Comment by alexjp** [comment]
I was thinking more or less the same, but on reddit :)

**Comment by psifidotos** [comment]
why not... :)

I had also an another idea... When a bug is tagged "upstream" then it means ...awaiting to be reported... if someone reports it upstream it would be nice to comment here the link... and I could add after that a second tag "reported!"... This will help a lot to know where the discussions are happening for upstream issues...

**Comment by alexjp** [comment]
Its a good idea ... 

I will schedule for tomorrow to do some bug reporting, since its very late here ( 1 am )

**Comment by psifidotos** [comment]
perfect!!! :) 

no pressure on time!! :) we are here to stay... :)

Now Dock is already at a very good shape for such an early development stage, I am developing it for 1.5 months only... Issues that are found and arised upstream i have the patience to wait for them...

For example the transparent panels for Plasma 5.9 was also a very good step... I must create an issue actually and report it as a feature request, even though plasma developers have already agreed for this... :)

**Comment by psifidotos** [comment]
not related to Now Dock.... feel free to report upstream and add links here...

**Comment by alexjp** [comment]
Reported, link on first comment. You can add the reported tag.

**Comment by psifidotos** [comment]
and you have also a response from Martin ! :)
