### ISSUE TITLE
Some icons used from plasma theme

### ISSUE THREAD

**Issue by varlesh** [psifidotos/nowdock-plasmoid#3]
For example KTorrent and Akregator used from Plasma Theme. That not good look for dock.
![image](https://cloud.githubusercontent.com/assets/8083855/17642568/aa588daa-6153-11e6-876e-19808cad9c4d.png)
On Icon theme (Papirus) this monochrome icons not available - that icons only on plasma theme.
![image](https://cloud.githubusercontent.com/assets/8083855/17642574/0097d7de-6154-11e6-8799-e9629d264efe.png)

**Comment by psifidotos** [comment]
Papirus... :) beautiful icon theme, I didnt know it.

If I understood correctly, you are saying that for the icons that do not exist in the Papirus icon theme the Plasma theme ones should be used?

**Comment by varlesh** [comment]
Icons on dock (akregator and ktorrent) used from plasma theme - this icons for tray only.
For example:
https://github.com/PapirusDevelopmentTeam/papirus-plasma-theme/tree/master/papirus/icons

**Comment by varlesh** [comment]
left to right (on screen)
1 icon = akregator
5 icon - ktorrent (or qbittorrent)

**Comment by varlesh** [comment]
On widget tasks (icons only) used only icons from system icon theme.
![image](https://cloud.githubusercontent.com/assets/8083855/17642768/7ebba804-615c-11e6-8d36-cce292fc3cb7.png)
But for tray use another icons (if available on plasma theme)
![image](https://cloud.githubusercontent.com/assets/8083855/17642783/bc537994-615c-11e6-94ea-25b83ed8c1e8.png)

**Comment by psifidotos** [comment]
Ohhhhh, my plasmoid uses the tray use ones in some cases ???

**Comment by varlesh** [comment]
yes, if available on plasma theme

**Comment by psifidotos** [comment]
should be fixed !!!! :-)

**Comment by varlesh** [comment]
If you use Breeze icon theme (apply Breeze plasma theme too) and see - akregator icon (or amarok, ktorrent and etc) will be used from plasma

**Comment by varlesh** [comment]
All ok 👍 
![image](https://cloud.githubusercontent.com/assets/8083855/17642885/a79a1342-6160-11e6-8f6f-d5cea5087ee6.png)

**Comment by psifidotos** [comment]
;-) :+1:
