### ISSUE TITLE
Blurry icons

### ISSUE THREAD

**Issue by SteveKej** [psifidotos/nowdock-plasmoid#30]
Again thanks Michail,  I really like this project!

One thing I've noticed is that when icons zoom, they look slightly blurry:
Normal:
![image](https://cloud.githubusercontent.com/assets/1503819/18294360/764db814-7490-11e6-987d-43be8df52c51.png)
Zoomed:
![image](https://cloud.githubusercontent.com/assets/1503819/18294394/bcedb0a8-7490-11e6-97ad-9dc9a4d789ac.png)

Here I'm using 40px icons at 1.9% zoom.

Maybe it's the highlighting, although the partly scaled konsole icon looks a bit blurry to me.  I've no idea if this is the case, but It seems as if the 40px icons are being scaled up.  Maybe it would be possible to 'reverse' scale larger icons down to create the effect, if this is indeed the case?

I hope that makes sense.

Cheers!

**Comment by psifidotos** [comment]
The question is ... How did you set a 40 px icon? :)

**Comment by SteveKej** [comment]
Oops sorry that should be 32 px!

**Comment by psifidotos** [comment]
If I remember correctly if you use factor 2, the blurring will dissappear...

am I right?

**Comment by SteveKej** [comment]
Yes indeed.  Thanks for that :)

**Comment by psifidotos** [comment]
no worries... :)

it is a case that I am thinking even I could do better actually...

**Comment by psifidotos** [comment]
to support also a little better the zoom factors 1.5-2.0 for icon size 32 and 48

**Comment by kupiqu** [comment]
Would scaling down instead of up generate artifacts? If not, I still think this was a good idea as some users may think x2 is too much of a difference...

**Comment by psifidotos** [comment]
actually 1.5 -2.0 for icon size 48 is ok... so a little better for 1.5-2 for 32px.... I will look into it the next days...

**Comment by psifidotos** [comment]
I will try to change the internal infrastructure to improve this... Until now I was using PlasmaCore.IconItems, I will try to support QIconItems which do not have so many issues with sizes below 48... I hope only that the buffering mechanism will pass the memory tests...

We 'll see....

**Comment by psifidotos** [comment]
so.... QIconItems didnt pass the memory tests... so I tried to workaround a bit for this...

@SteveKej, @kupiqu 

could you please check the #newbuffers branch if it fixes or improves this issue in small icon sizes?

**Comment by SteveKej** [comment]
It's somewhat improved. Looking critically, I still notice some blur at certain points during the zoom animation.  It's final zoomed state is fine though. Using 32px @1.9 zoom as before.

There was also some weirdness when adding launchers and dragging them in that they started using the wrong app's icon.  Restarting plasma seemed to stabilise that.  Also some settings are greyed-out.

**Comment by psifidotos** [comment]
- the new now-dock panel greyes out the settings which are its own resposibility... You can access these settings by unlocking widgets  and use the new configuration button of the panel..
- the weirdness about using wrong app's icon, it must be investigated if it remains... please inform me about that
- for the blurring I dont think that anything else can happen... blurring during animation is normal behavior, concern has been made only for normal state and full hovered state(and this there are some edge cases that they are a little blurred but I dont think I can do any better...

**Comment by psifidotos** [comment]
> @kupiqu  Would scaling down instead of up generate artifacts? If not, I still think this was a good idea as some users may think x2 is too much of a difference...

the scaling uses two buffers...
one for normal showing zoom: 1 and one for full hovering e.g. zoom factor:1.7,
in the middle the buffers are swapped. So when reaching 1.7 the zoomed buffer is used and when reaching 1 the normal buffer is used....

**Comment by SteveKej** [comment]
Ok I was using an older version of the now-dock panel.  I've installed the latest master and tested the settings there and it's resolved the icon weirdness issue too, so no worries there.

As I mentioned before, the zoom blur is only noticeable when looking at it critically.  It seems that it only briefly becomes apparent when approaching the point that the buffers are swapped.

**Comment by psifidotos** [comment]
> @SteveKej  It seems that it only briefly becomes apparent when approaching the point that the buffers are swapped.

yes, that is correct... I could drop the two buffers and enable only one for the shadows but that would increase cpu usage... This is why I have made that design decision... Either way there are **no** icons for in between cases e.g. for sizes between 32 to 48, and 48 to 64, so some blurring I think its normal...

**Comment by kupiqu** [comment]
I also tested it and it works as good as it can, I would say.

A very naive question, would it not be possible to use svg versions of the icons instead? I guess that is not an option but for such animations it would be just the best option...

**Comment by psifidotos** [comment]
@kupiqu would it not be possible to use svg versions of the icons instead?

i dont know any way to do this.
The icon behavior is the default from plasma. Plasma uses the svgs after the maximum available size. If I have understood correctly, it uses svgs after 48px. or 64px. based on the theme's offering...

**Comment by kupiqu** [comment]
mmm, I foresee room for a feature request related to this at kde bugs: allow option to use svg icons for animations that require icon scaling...

Would you agree?

I can try so submit a bug report tonight

**Comment by psifidotos** [comment]
I think that we must ask first the plasma developers if there is a way to
use the svg versions for icons from theme for sizes below 64... I found
also this article describing the way it functions:
http://www.notmart.org/index.php/Software/New_QML_components:_IconItem

**Comment by psifidotos** [comment]
fixed in master...  I dont know about the svg use ...

**Comment by kupiqu** [comment]
Do we have a channel to ask the right person about the svg use by default (if available)?

**Comment by psifidotos** [comment]
> Do we have a channel to ask the right person about the svg use by 
> default (if available)?
> 
> There is the plasma-devel mailing list and of course the #plasma irc 
> channel...
