### ISSUE TITLE
Icon sort/order

### ISSUE THREAD

**Issue by alexjp** [psifidotos/nowdock-plasmoid#31]
Hi,

I have two "all activcities" launchers, dolphin and konsole, and they are always the top ones.

Sometimes, "launched launchers" will go up to the top. Is it possible to keep ordering ?

Example:

![screenshot_20160907_084855](https://cloud.githubusercontent.com/assets/85806/18304108/6d411bd8-74d8-11e6-8fbe-fa2a947f2418.png)

In this window, kmail is openned on my other monitor. It is not normally on the top, but because its openned, it got into the top. This usually happens when i switch activities and came back.

**Comment by psifidotos** [comment]
I have noticed also... I dont know the answer actually... the behavior we see is that the opened launchers are ordered first... we will see what  is going on...

This is based  a lot on how libtaskmanager decides to order the launchers after a launcher list update has happened...

**Comment by alexjp** [comment]
I actually had this bug a while ago : https://bugs.kde.org/show_bug.cgi?id=364212

But its supposed to be fixed, at least on normal taskmanager seems to be.

**Comment by psifidotos** [comment]
but normal taskmanager is not making a launchers list update in every activity switching...

**Comment by alexjp** [comment]
There was a bug in the first versions of the new taskmanager, where launching an app would make it go into the left.

> but normal taskmanager is not making a launchers list update in every activity switching...

I dunno if its doing it or not, but may be doing it, only its only seen on nowdock because of the animations.

One common cause is that they are ordered, but when switching activities they lose their order.

When i have a bit of time i will check the taskmanager git log and try to check what was done.

**Comment by psifidotos** [comment]
> I dunno if its doing it or not, but may be doing it, only its only seen on nowdock because of the animations.

it isnt the taskmanager which is doing it... it is the nowdock plasmoid...

I have implemented to update the whole launcher list in each activity switching...
I thought that this would be the only way to keep the ordering right...

I could try to make removals and additions for launchers between activity switching instead of full initialization but I fear that the activity launchers order will break probably...

**Comment by psifidotos** [comment]
this needs research, in order to understand if this is from my current implementation or from the libtaskmanager not taking into account the use case (update launchers list after the first publishing)

**Comment by psifidotos** [comment]
@alexjp can you please test that this is happening also for the lanchers which are "**Not** On All Activities"  ?

**Comment by alexjp** [comment]
@psifidotos from my experience, this is happening especially on launchers which are "not on all activities", since I only have 2 "All activities" launchers.

Right now I have an example of "Not On All Activities" launchers, on one activity it became first icon, and on another, it became the last icon.

**Comment by psifidotos** [comment]
@kupiqu , actually I can fix this for the startup... But, the only way to workaround this when changing activities an initialization is needed... Which means that I should hide all icons and then show them again...

**Comment by kupiqu** [comment]
I think this would be ok, wouldn't it? I mean plasma desktop is being reload when this happens, so one may be tolerant about transient adjustments that need to be done to come back to normal behavior, in my opinion...

**Comment by kupiqu** [comment]
Was talking about startup, about activity changes, I'm not sure, although personally I would prefer to keep sorting at all cost, including re-initialization :/

**Comment by psifidotos** [comment]
... this is a mess ... check the sortorder branch... This is upstream... Providing a different launcher list makes the task model to behave like this... My opinion is that it shouldnt... I am just trying to workaround this behavior... I am not that positive that this will succeed...

**Comment by kupiqu** [comment]
I tested it. It doesn't seem to work for me. 

If this is upstream, I would just forget about it for now

**Comment by psifidotos** [comment]
From nowhere... I probably found a workaround !!! Please check branch **sortorder2**, it should fix this in most cases.... The only issue is that OnAllActivities launchers can not be mixed yet with "Spesific Activity" ones... So the ordering for them would be... 

"OnAllActivities" correct ordering, "Spesific Activities" correct ordering, rest of windows...

**Comment by psifidotos** [comment]
@kupiqu  please check again **sortorder2**....

**Comment by kupiqu** [comment]
It still does weird things in my system, icons missing, and on hovering things move a bit crazy up and down, with empty spaces :/

All my applications appear in all activities, for the case this is useful

**Comment by psifidotos** [comment]
@kupiqu are you sure you are using **sortorder2** ? this is different than the **sortorder**...

**Comment by psifidotos** [comment]
@kupiqu I have just uploaded a small fix that may fix things for you...

**Comment by kupiqu** [comment]
Yes, I'm using sortorder2. Unfortunately, it doesn't work properly here yet. Some icons appear now on top of others.

**Comment by psifidotos** [comment]
in my system works perfectly... maybe an initialization? remove all launchers and try again?

**Comment by psifidotos** [comment]
and maybe a screenshot...

**Comment by kupiqu** [comment]
Will test in a new plasmoid and will let you know

**Comment by alexjp** [comment]
> in my system works perfectly... maybe an initialization? remove all launchers and try again?

I didn't do alot of testing, just openning launchers from the 3 kinds ( all activities, this activity , one time launcher ) and switching activities like mad , and everything seemed ok, all launchers were in the right order.

**Comment by psifidotos** [comment]
@alexjp I think it is possible now with the new fix to support mixing all activities launchers and per activity launchers and the internals could remember their orders per activity... That needs an update in the internals but I think it can be done... What do you think?

@kupiqu did you have any update in this? There is a chance also that the new plasmoid version from sortorder2 has been updated correctly in your system... It sometimes happens... You could also try to remove the plasmoid and then re-install it...

**Comment by alexjp** [comment]
> @alexjp I think it is possible now with the new fix to support mixing all activities launchers and per activity launchers and the internals could remember their orders per activity... That needs an update in the internals but I think it can be done... What do you think?

Seems to already work on the branch sortorder2 .... haven't catched any problem till now

**Comment by psifidotos** [comment]
@alexjp what I am describing is an advance situation :) for example .... I have 3 launchers, a firefox(all activities), a dolphin (all activities) and a kwrite(specific activity). I drag kwrite **between** firefox and dolphin... After the activity change the launchers are ordered based on their type, so it will be firefox, dolphin, kwrite...

I think that because of the new fix it would be possible to have (per activity) launchers between (all activities) launchers, and Now Dock would restore their ordering even in this advance situation...

**Comment by alexjp** [comment]
@psifidotos sorry, misunderstood ... i thought you were talking about mixing them as in having them on the dock and them being ordered. Never though on actually putting a "single activity launcher" between "all activity launchers".

**Comment by psifidotos** [comment]
@alexjp me too... :) I like the ordering of being first the global launchers and after them following the specific activity's  ones.... I am just taking opinions.. :) I can leave this for a later release (above 0.4) if the users find it useful...

**Comment by psifidotos** [comment]
eveything in **master** branches for panel and plasmoid and small fixes ... Last days before **0.3** release... :-)

**Comment by kupiqu** [comment]
Sorry, I had to deal with a deadline, and won't be able to test this further until Tomorrow (still experiencing issues, but this might be because my plasma desktop rc file is quite messy, I will try to start it from scratch and will see).

**Comment by psifidotos** [comment]
:+1: let me know @kupiqu

**Comment by psifidotos** [comment]
@kupiqu, and please **uninstall** every prior version of the plasmoid and the panel before using the master branches!! There is a change in their names that could create two different instances for each one...

**Comment by kupiqu** [comment]
I reconfigured my plasma desktop from scratch and used last master versions of nowdock panel and plasmoid, however, I am experiencing the same behavior.

Reached this point, I'm not sure whether I explained my issue quite properly. I am referring to the following case, please try to reproduce:
1. Open some apps that are launchers in nowdock plasmoid
2. kquitapp plasmashell
3. kstart plasmashell

expected behavior:
- launchers appear as previously configured

seen behavior:
- it is quite random: some launchers appear out of place, sometimes overlapping others, sometimes empty spaces around.

please see screenshots for an example:
- order as configured:

<img width="39" alt="screenshot_20160917_025706" src="https://cloud.githubusercontent.com/assets/3875196/18606601/a20602d2-7c82-11e6-9036-674d968aa7f6.png">
- after reloading plasmashell:

<img width="38" alt="screenshot_20160917_025601" src="https://cloud.githubusercontent.com/assets/3875196/18606610/c4dcfe3c-7c82-11e6-9534-766044b761f7.png">

Please note in the example how Kate's icon has moved and now overlaps Konqueror's icon.

**Comment by psifidotos** [comment]
@kupiqu  which of them are the launchers?

**Comment by psifidotos** [comment]
@kupiqu, as I see it everything is in place except the konqueror and kwrite that have swaped positions... The question is why the konqueror icon is not shown...

**Comment by kupiqu** [comment]
Re launchers: First one is system settings and last is spotify.

It is not that konqueror icon is not showing, but it is behind kate's icon and the other is empty. As I said, this is an example, and it is quite random, sometimes icons even go out of the plasmoid and overlap e.g. the application launcher (kde icon). I know it is an overlap because you see the other icon behind (unfortunately in previous example, kate's icon occupies all space and you cannot see konqueror's icon behind).

**Comment by kupiqu** [comment]
Would it help if I copy the settings of nowdock in plasma-org.kde.plasma.desktop-appletsrc and you add those to your file?

Perhaps you won't have some apps, but you can remove those before inserting the settings in plasma-org.kde.plasma.desktop-appletsrc. I think it would be the closest we can get to have something similar in your and my system.

[Containments][69]
activityId=
formfactor=3
immutability=1
lastScreen=0
location=5
plugin=org.kde.store.nowdock.panel
wallpaperplugin=org.kde.image

[Containments][69][Applets][71]
immutability=1
plugin=org.kde.milou

[Containments][69][Applets][72]
immutability=1
plugin=org.kde.plasma.kicker

[Containments][69][Applets][72][Configuration][General]
favoriteApps=systemsettings.desktop,org.kde.dolphin.desktop,org.kde.konsole.desktop,org.kde.kate.desktop,kde4-kile.desktop,org.kde.kontact.desktop,konqueror.desktop,chromium-browser.desktop,org.kde.dragonplayer.desktop,smplayer.desktop,spotify.desktop

[Containments][69][Applets][73]
immutability=1
plugin=org.kde.store.nowdock.plasmoid

[Containments][69][Applets][73][Configuration][ConfigDialog]
DialogHeight=780
DialogWidth=1040

[Containments][69][Applets][73][Configuration][General]
dotsOnActive=true
isInNowDockPanel=true
launchers=multi;*;11;file:///usr/share/applications/systemsettings.desktop;file:///usr/share/applications/org.kde.dolphin.desktop;file:///usr/share/applications/org.kde.konsole.desktop;file:///usr/share/applications/org.kde.kate.desktop;file:///usr/share/applications/kde4/kile.desktop;file:///usr/share/applications/org.kde.kontact.desktop;file:///home/jsardid/.local/share/applications/konqueror.desktop;file:///usr/share/applications/chromium-browser.desktop;file:///usr/share/applications/org.kde.dragonplayer.desktop;file:///usr/share/applications/smplayer.desktop;file:///home/jsardid/.local/share/applications/spotify.desktop
showGlow=false
showOnlyCurrentActivity=false
showShadows=false
showToolTips=true
threeColorsWindows=true

[Containments][69][Applets][74]
immutability=1
plugin=cqcb.plasma.webslice

[Containments][69][Applets][74][Configuration][ConfigDialog]
DialogHeight=780
DialogWidth=1040

[Containments][69][Applets][74][Configuration][General]
buttonBehaviour=true
displaySiteBehaviour=false
websliceUrl=http://192.168.0.1

[Containments][69][Applets][75]
immutability=1
plugin=org.kde.plasma.colorpicker

[Containments][69][Applets][76]
immutability=1
plugin=cqcb.plasma.webslice

[Containments][69][Applets][76][Configuration][ConfigDialog]
DialogHeight=780
DialogWidth=1040

[Containments][69][Applets][76][Configuration][General]
buttonBehaviour=true
displaySiteBehaviour=false
websliceUrl=http://192.168.0.1

[Containments][69][ConfigDialog]
DialogHeight=1440
DialogWidth=276

[Containments][69][General]
appletOrder=71;72;73;74;75;76
automaticIconSize=true
panelPosition=Top
panelSize=4
smallAutomaticIconJumps=true
useThemePanel=true
zoomLevel=5

**Comment by kupiqu** [comment]
I am just trying to help you reproduce the issue. Things that might be involved in some weird fashion:
- A weird combination of settings in nowdock, e.g. I don't use launchers that are activity specific, etc.
- The previous point related to some weird plasma bug upstream.
- A plasma packaging bug (I use KDE neon, perhaps you don't)
- Perhaps, simply a launcher that is misbehaving (although different icons are involved at different times).
- Some other configuration in plasma, not related to  plasma-org.kde.plasma.desktop-appletsrc that still interferes here somehow

Or perhaps some other issue that I cannot even imagine...

**Comment by psifidotos** [comment]
@kupiqu, this is not easy ... I tried your configuration already and I didnt have any issues... I use opensuse with plasma 5.7...

let's try something else... try please the **blanks** branch for the plasmoid and tell if you have same issues... In this branch I have disabled the reordering of launchers.. your launchers will no appear in the correct order but at least we will know where is the problem...

**Comment by kupiqu** [comment]
I'm going to try it, but please note that my problem was not present before introducing the feature to reorder launchers (which, if I recall properly, I suggested)

**Comment by kupiqu** [comment]
Another example:

<img width="38" alt="screenshot_20160917_090500" src="https://cloud.githubusercontent.com/assets/3875196/18608412/60e637ac-7cb6-11e6-8f9e-36f790427c8f.png">

**Comment by psifidotos** [comment]
it is important to try it, because it you dont have any issues then this means that reordering in your system happens in a time that breaks your experience... Currently the reordering happens just before adding the launcher...

**Comment by kupiqu** [comment]
Without reordering I don't see any issue (besides the obvious of the ordering itself, of course):

<img width="38" alt="screenshot_20160917_091406" src="https://cloud.githubusercontent.com/assets/3875196/18608432/197f8232-7cb7-11e6-8d91-b127c14ef2ee.png">

**Comment by kupiqu** [comment]
I will keep the plasmoid in this branch for now until the issue is fixed :)

But let me know if you want me to test more...

**Comment by psifidotos** [comment]
ok... let's try to make the reordering after the launcher has ended its animation...

please, try again!

**Comment by psifidotos** [comment]
@kupiqu dont bother... doesnt help....

**Comment by kupiqu** [comment]
did I say sth wrong? if so, it was unintentional...

**Comment by psifidotos** [comment]
@kupiqu no, no... I was referring to the previous commit in @blank branch... I was hopping to help but it didnt...

**Comment by kupiqu** [comment]
Ok let me know if you want me to test at at some point :)

**Comment by psifidotos** [comment]
I am trying to change a bit the architecture... I will have something in a while...

**Comment by kupiqu** [comment]
+1

**Comment by psifidotos** [comment]
@kupiqu please test **blanks3**

**Comment by kupiqu** [comment]
I'm away from my computer, but I'll test it as soon as I come back

**Comment by psifidotos** [comment]
:+1:

**Comment by kupiqu** [comment]
It works better. No more overlaps, and I would say that most of the launchers now appear at right location, but unfortunately there are still a couple that are misplaced

**Comment by psifidotos** [comment]
@kupiqu, in file TaskDelegate.qml, line: 820, there is the line:
interval:800

if you try to increase it... for example to:
interval:2000
does it work better in your system then?

**Comment by psifidotos** [comment]
@kupiqu and I have just uploaded one more fix that it might help for you...

**Comment by kupiqu** [comment]
I think last commit did it!!

Let me test it a bit more to confirm...

**Comment by psifidotos** [comment]
crossing fingers here!!!! :)

**Comment by kupiqu** [comment]
I have tested it several times and I am quite confident now that it works properly in my system :)

**Comment by kupiqu** [comment]
Many thanks for the patience, effort and good work!

**Comment by psifidotos** [comment]
Nice to hear, dont mention it !!!! :) Let's have a beautiful release tomorrow!! :)
