### ISSUE TITLE
NowDock when its on a autohide panel

### ISSUE THREAD

**Issue by alexjp** [psifidotos/nowdock-plasmoid#33]
Hi,

I noticed that when nowdock is in an auto hidden panel, it doesnt update its state or drawing.

For example: I notice that if the panel is hidden and i change activities, even if I wait 10 seconds, only when panel is visible again, nowdock updates its icons.

Would it be possible for nowdock to update its size and icons while hidden ? Would make up for a much smoother effect. ( also kwin master branch for 5.8 has that panel unhide effect like KDE4, would look sweet for the dock )

Thanks.

**Comment by psifidotos** [comment]
> Would it be possible for nowdock to update its size and icons while hidden ? 

actually l dont know... this is totally plasma related...

**Comment by psifidotos** [comment]
this is full upstream related... feel free to report and add links here...
