### ISSUE TITLE
asymmetric lateral margins when the panel anchor is set other than centered

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/nowdock-plasmoid#34]
this is a rather minor thing, but it would be nice to decrease the ending lateral margin that is opposite to the anchor, so the panel looks symmetric

note: perhaps this should be set as an issue for the panel but not sure all the people uses the panel

**Comment by psifidotos** [comment]
> this is a rather minor thing, but it would be nice to decrease the 
> ending lateral margin that is opposite to the anchor, so the panel 
> looks symmetric
> 
> note: perhaps this should be set as an issue for the panel but not 
> sure all the people uses the panel

for panel issues consider reporting directly to corresponding page:
https://github.com/psifidotos/nowdock-panel/issues/

concerning what you are describing, the ending lateral margin is not 
taken into account even in the current implementation. I believe that by 
setting default the bounce animation to use
zoomFactor *(iconSize+margin)  //this margin is not the latter but the 
first which is near the dots and lines

and taking into account the above size into computations the space you 
are describing that is not needed will simple disappear....

So in this case for everything the maximum needed space will be:
zoomFactor *(iconSize+margin) // which is also the one of the hover 
animation

**Comment by psifidotos** [comment]
sorry... I just noticed that you are describing a different thing from what I undestood previously...

please report this to Now Dock Panel:
https://github.com/psifidotos/nowdock-panel/issues/

and I would like a screenshot also to understand about what margin you are describing and what you want to achieve....
