### ISSUE TITLE
Branch svgs: Some icons have a thick black border

### ISSUE THREAD

**Issue by alexjp** [psifidotos/nowdock-plasmoid#36]
Hi,

Its weird, but happening only in the svgs branch, some icons have a thick black border in them.

See -> [Image](http://imgur.com/a/TfzD7)

Icons: Hangouts and Tweetdeck ( Reddit is also a little weird )

Thanks !

**Comment by psifidotos** [comment]
if you have enabled shadows maybe it is an issue with them... Can you check again the latest commit in svgs for this? Does it get any better?

notice: the reddit icon is a wrong shadow issue
for the hangouts and tweetdeck what should I observe???? I dont see the black border...

**Comment by alexjp** [comment]
See for example [Image](http://imgur.com/KHOf1KE) as to how hangouts and tweetdeck look like. It doesnt have that black border.

I will test with latest commit

**Comment by alexjp** [comment]
checked latest commit, doesn't fix it.

Also, i don't have shadows enabled while testing this.

**Comment by alexjp** [comment]
This video catches the problem: https://youtu.be/xlpqgfi48dM

**Comment by alexjp** [comment]
Basicly changing between size 48x48 and 128x128 versions of the hangouts icon

**Comment by psifidotos** [comment]
very strange... dont you think?

**Comment by psifidotos** [comment]
can you send alex the icon 128px. that creates the issue? even though I think that this is very strange...

**Comment by alexjp** [comment]
Yes, very strange. More info:

I rebooted computer and issue seemed gone ! Then i reenabled shadows and the issue appeared again. Then i disabled them again, and it was gone again.

**Comment by alexjp** [comment]
you can check out the icons in: https://we.tl/m6NomeI37R

I even put there all the icons i have locally ( not part of system )

**Comment by psifidotos** [comment]
yes...
that is normal.... 
the latest commits in svgs branches were fixing this issue for disabling the shadows

what you are seeing is the shadow buffer... Unfortunately for that specific icon can not be drawn correctly ... And I dont know why.... Can you send me the problematic icon to play with it?

**Comment by alexjp** [comment]
> Can you send me the problematic icon to play with it?

You have in the previous link both hangout icon and tweetdeck icon.

**Comment by psifidotos** [comment]
alex, in my system it happened only once when i changed the icon to the 128px. version manually...
After that there is no issue... Especially if I trigger the launcher...
Can you try to remove all alternative sizes for this icon and keep only the 128px one?

**Comment by psifidotos** [comment]
ok ... I fixed it in [svgs] branch .... I used an IconChanged signal to update the shadow buffers... this should always have correct shadow...

**Comment by psifidotos** [comment]
ok!! merged svgs to master !!!

@alexjp  first thing to merge your branch!!! Debug a little !! And then we ready to launch 0.3 !!! :)

**Comment by alexjp** [comment]
Sorry ... was busy, wasnt following this.

Nice !!! I will merge master and my changes and test. Until now I didn't found any problem, but who knows.
