### ISSUE TITLE
Restore proper icon order when plasmashell restarts

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/nowdock-plasmoid#38]
Not sure whether this is an upstream bug or not, but it would be great to restore the proper order of icons if plasmashell is reload (e.g., by doing kquiapp plasmashell and then kstart plasmashell).

Currently the problem is that active windows of the desktop appear first, irrespective of the order in which these applications appear in the settings of nowdock plasmoid.

**Comment by psifidotos** [comment]
#31
