### ISSUE TITLE
Proper way of using plasma-transparent-panel.py.v0.2.2 (does it really work?)

### ISSUE THREAD

**Issue by seppd** [psifidotos/nowdock-plasmoid#40]
I issued 
`python transparentpanel.py breeze South`
and then selected newly created theme Breeze - South Transparent. But the South Pannel still was not transparent, i.e. the theme had no effect.
Did I make smoething in a wrong way? I'm using plasma 5.7.5 on Archlinux.

Thank you!

**Comment by kupiqu** [comment]
This might be related to background contrast in desktop effects. Try disabling it...

**Comment by psifidotos** [comment]
You have to disable the following Desktop Effects:
- Blur
- Background Contrast

**Comment by seppd** [comment]
Yep, disabling only Background Contrast does the job. Thaks!
