### ISSUE TITLE
What is next for 0.4?

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/nowdock-plasmoid#41]
Hello everyone...

I would love to have your feedback around 0.3 and what do you think it should get into 0.4...
- _There is a discussion around **spacers** for Now Dock Panel, would you find it useful?_
- _Now Dock 0.4 I think it should be full compatible with Plasma 5.8_
- _what else ?..._

**Comment by kupiqu** [comment]
I fully agree on these two. I cannot think of anything else for now :)

**Comment by psifidotos** [comment]
@kupiqu, concerning the spacers... What I have in my mind is to split the plasmoids to the two edges... for example, in the bottom panel there could be applets at the left and the right edges, but not in the center...
Would you find that sufficient? The complexity to add this feature is big, so this is why I am asking your opinion and why I am trying to avoid center placement when the user has added spacers...

**Comment by kupiqu** [comment]
Yes, I think that's fine

**Comment by alexjp** [comment]
@psifidotos Concerning spacers, please also consider that users are "used to" panel spacers.
I thinks its a good idea, but will be different than normal panel.

**Comment by psifidotos** [comment]
@alexjp, can you describe then how it should behave the Now Dock Panel with spacers? what do you have in mind?

**Comment by alexjp** [comment]
> @alexjp, can you describe then how it should behave the Now Dock Panel with spacers? what do you have in mind?

Just the normal panel spacer. I use nowdock plasmoid with normal panel and it works well with the spacer.

Could you use the code from the normal panel's spacers ?

**Comment by psifidotos** [comment]
@alexjp, this is not that simple... Now Dock takes into account the growing mechanism... For example in left anchoring the plasmoids are growing to the right but in right anchoring are going to the left... This must be supported at the same time... So this is not the default panel's behavior....

The Behavior that I have in my mind is the following... 
- The user will add a panel spacer which is going to be the limit that will separate the plasmoids to left and right. If the user adds a second spacer  this is not going to have any impact, the second spacer will add just a small space...
- In order to return to the default Now Dock Panel behavior the user must remove all added spacers
- the spacers which are going to be used are just those of the plasma's default panels
- when the user is in configuration mode then all plasmoids are going to placed in the center with also their spacers, in order to be able to move, add, remove the plasmoids and the spacers also
- if the user adds a second spacer, I dont think it will be easy to support alligning the plasmoids left, center and right **at the same time** and **growing** differently
- the supported case would be a spacer just aligns the plasmoids left and right

**Comment by alexjp** [comment]
@psifidotos I guess the left and right alignment behaviour is good. ( I think that is the only reason I also use spacers ).

Maybe for "just adding a small space", instead of spacers, adding a "Separator". Separators seem very common in docks.

Something along the like "Spacer" ( witch is an alignment spacer ) and "Separator" ( witch is a fixed size separator )

What do you think ?

**Comment by psifidotos** [comment]
@alexjp, I can not understand what do you mean by "Separator".
Can you give me a screenshot ? What is the difference with "Spacer" ?

**Comment by alexjp** [comment]
@psifidotos for example something like this: 
https://goo.gl/waQugm
that little spacer

**Comment by alexjp** [comment]
In our case, something like this: ( the vertical 5 or so px line )
https://goo.gl/U00gE1

( because there is no 3d effect in plasma )

**Comment by psifidotos** [comment]
this could be a very simple plasmoid... there is the Separator plasmoid but didnt work for me... We could create something easily I think... But a new Separator plasmoid is not going to be inside the Now Dock Panel code page... It could be able to be used everywhere even in the default panel....

**Comment by psifidotos** [comment]
the spacers of macs, e.g. http://lifehacker.com/5993307/easily-add-spacers-to-your-macs-dock is already supported is the current behavior of the Now Dock Panel when the user adds spacers...

**Comment by alexjp** [comment]
ok, I was just trying to see if was worth separating the notion of "spacer that aligns" and "spacer that just adds a little space", as only one "spacer" can cause aligning.

**Comment by psifidotos** [comment]
@alexjp you have a point... Spacers in that implementation belong to two different categories... To give the user so much power, e.g. having a special spacer(for aligning separation) to put everywhere he wants even after normal spacers is very interesting use case but on the implementation side demands a lot!!!

for example we could colorize that special spacer differently in order to distinguish it from the others (and not use just the first to be found...) 

we'll see... when I start playing with all this (spacers support) I will find the limitations that exist...

As I see it Now Dock Panel supports so many different anchorings except **only central** that already distinguish it from alternatives...
Adding spacers and using different anchors at the same time is one more step further...

I hope that we will make it happen...

**Comment by s8321414** [comment]
Can you make it translatable (localizable)?

**Comment by psifidotos** [comment]
@s8321414 I dont know yet if it is possible to distribute .mo files (localizations) inside a .plasmoid file... If this is possible then from my side it can be done... If this is not possible then the distribution channel must change, so I dont think an 1-click install from store.kde.org will be possible.... 

Either the user should install it manually or install it from the distributions repos...

**Comment by s8321414** [comment]
https://github.com/dimkard/distrowatcher
Maybe you really need to modify something...

**Comment by psifidotos** [comment]
@s8321414 I dont disagree... the link you sent me provides two ways of installation.... the second one "plasmapkg -i distrowatcher.plasmoid" which is used also for 1-Click installations does not have alternative translations in it...

The user must use the first way to install the plasmoid, and that way is not the 1-Click install way....

**Installation (version 1.*)**
- Unzip the plasmoid
- $ mkdir build
- $ cd build
- $ cmake -DCMAKE_INSTALL_PREFIX=/usr .. 
- $ make
- $ (sudo) make install
- "Distro Watcher" widget is now available to add to desktop/panel.

**Comment by psifidotos** [comment]
@s8321414 ...
there is #42  concerning localization support...
If anyone wants to help in this...
my pleasure...

**Comment by psifidotos** [comment]
@s8321414 do you want to help in localization? 

@alexjp spacers and double layout is going much smoother that I was expecting... :) the next days I am going to have something to test if you want...

**Comment by s8321414** [comment]
@psifidotos Of course, sure!

**Comment by psifidotos** [comment]
@s8321414 nice to hear!!! :) can you help in qml also? to insert the _**i18n(...)**_ syntaxes where they are needed in order to support translation for that texts?

**Comment by psifidotos** [comment]
@alexjp @kupiqu 
can you please test the new splitter mechanism in **Now Dock Panel** ? **[master]** branch?

There is a fourth layout supported now, "Left | Right" and "Top | Bottom" for which the user can decide between two different places to put its plasmoids... :-)

**Comment by s8321414** [comment]
@psifidotos How can I do for this?

**Comment by psifidotos** [comment]
@s8321414 finishing early with the spacers issue and the splitter layout in Now Dock Panel, I started implementing localization... Dont worry about qml but I would like a tester !! 

I will support localization first for the Now Dock Panel which doesnt have so many texts to be translated in order to test the new way of organizing things...
1. update Now Dock Panel for localization support
2. upload to **transifex** the needed texts to be translated
3. just test that all this is going smoothly with no drawbacks
4. after Now Dock Panel is ok and translatable I will use the same way to do this for Now Dock Plasmoid

will you be able to test Now Dock Panel later today or tomorrow when it is ready?

**Comment by kupiqu** [comment]
Wow, working great, I think I'm going to use it from now on in Top|Bottom mode

**Comment by psifidotos** [comment]
@kupiqu nice to hear... ;)

**Comment by s8321414** [comment]
@psifidotos Fine, thank you! :smile:

**Comment by psifidotos** [comment]
@s8321414 Now Dock Panel is ready for translations...

anyone interested to translate it can use:
https://www.transifex.com/psifidotos/now-dock-panel/

in the next days same architecture will happen also for the Now Dock Plasmoid

**Comment by psifidotos** [comment]
Forget transifex... I didnt like it...

Go old fashion if you want to translate it, through pot and po files...

**Comment by psifidotos** [comment]
I created some installation/uninstallation scripts for **Now Dock Panel** in order to help with the new localization infrastructure...

**Comment by s8321414** [comment]
hm? so how can we translate it? Just fork it and translate and make a PR?

**Comment by psifidotos** [comment]
**Important Notice - This is only for Now Dock Panel for now... the next days the plasmoid will be also ready...**

@s8321414 yes...
1. fork it
2. use file **po/plasma_applet_org.kde.store.nowdock.panel.pot** from which to produce your translated **po/<lang>.po** file
3. make a **Pull Request** in order to commit it in the project

**alternative**
1. download file **po/plasma_applet_org.kde.store.nowdock.panel.pot** from which you produce your translated **po/<lang>.po** file
2. upload your translation to forum: https://github.com/psifidotos/nowdock-panel/issues/17

**Comment by psifidotos** [comment]
So.... :-) faster than I had in my mind....

You can now translate also the plasmoid... :) happy translations!!! :) and have fun....

**Comment by s8321414** [comment]
OK, I will do it recently :smiley:

**Comment by psifidotos** [comment]
@kupiqu @SteveKej  @s8321414 @alexjp 

do you know if you have any issues with Now Dock Panel one-click installation for Plasma 5.8 ?
https://github.com/psifidotos/nowdock-panel/issues/19

**Comment by kupiqu** [comment]
Sorry, not yet in Plasma 5.8

**Comment by s8321414** [comment]
I'm still on Plasma 5.7.5

**Comment by psifidotos** [comment]
me too...
I will update to 5.8.0 as soon as it is released... 
I suppose that in order to fix the various issues Now Dock 0.4 will break compatibility with Plasma 5.7...

**Comment by psifidotos** [comment]
Well.. I have added in Now Dock Panel for the manual installation a default Now Dock default layout which adds a Now Dock plasmoid and a clock by default...

My future plan is that in the next days I will upload the last 0.3 versions (5.7 compatible) of Now Dock Panel and plasmoid which will support all the latest commits (including spacers and small fixes and animations) 
and after that the master branches are going to move to Plasma 5.8 in order to prepare the 0.4 versions with all the needed fixes...

**Comment by psifidotos** [comment]
so for translators some new strings exist in panel translations... whoever needs translations must install through global installations. The local installations or 1-click from store.kde.org do not have the translations and the default layout for the panel....

**Comment by s8321414** [comment]
So will have 0.3.1?

**Comment by psifidotos** [comment]
@s8321414 for the plasmoid there will be 0.3.2(0.3.1 exists already in store.kde.org) and for the panel 0.3.1, these will be the last versions for 0.3 branch... After that everything goes to master and 0.4 branch (only Plasma 5.8 compatible)

**Comment by psifidotos** [comment]
@s8321414 so, last 0.3 versions are out...

**for the 0.3 branch only small fixes and new translations if someone requests it...**

**Comment by s8321414** [comment]
@psifidotos Great! I already packaged it!

**Comment by psifidotos** [comment]
@s8321414 :+1: for you? or for a distro?

**Comment by s8321414** [comment]
@psifidotos For [Chakra GNU/Linux](https://chakralinux.org/)

**Comment by psifidotos** [comment]
@s8321414 :+1:   Fantastic!!! Thank u !!!

**Comment by lucasslima** [comment]
Having window management options, such as maximize or minimize would be very helpful for me. :)

**Comment by psifidotos** [comment]
@lucasslima ok.... but in order to not create clutter in the menu I am thinking that the user should first enable them from the configuration window....

**Comment by lucasslima** [comment]
@psifidotos I agree. I only asked because sometimes I have to handle a bunch of windows, and I need to be able to minimize or maximize all of them.But I understand your concern with cluttering the  menu.

**Comment by psifidotos** [comment]
@lucasslima ok... this is in master now if you want to test it...

**Comment by psifidotos** [comment]
**Important**, new translation strings in master branches.....

**Comment by psifidotos** [comment]
**update**, new translation strings for now dock panel, I have added more options for shadows in the panel (none, only for locked applets and to all)

**Comment by psifidotos** [comment]
I believe that both the panel and the plasmoid are ready for the 0.4 release.... So  the next days both 0.4 versions which are 5.8 compatible will be released....

**Comment by psifidotos** [comment]
v0.4 which is compatible with Plasma 5.8 was released....
