### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/nowdock-plasmoid#42]
support different languages...

**Comment by Steinhagen** [comment]
This should be added as soon as the codebase becomes stable.

**Comment by psifidotos** [comment]
unfortunately, I dont see it any time soon....

supporting this, it means two different approaches...
one way to install through **store.kde.org** without translations in it,
and an alternative to install manually or through distribution repos which will also provide the translations...

if anyone wants to begin this, my pleasure!!! This could also be a junior job !!!
what needs to be done:
1. every text in qml files that needs translation must get into i18n() function
2. after the above has been done I can produce the pot file and use **transifex** website for translators
3. provide the installation mechanism which will support this

**if anyone is interested to take over 1 or help in 3!! I am here!!! :)**

**Comment by psifidotos** [comment]
this is implemented in master...
