### ISSUE TITLE
Edited: Add an offset to background location, with default to 0 px. It was: Background location according to chosen option for dots and lines (top vs bottom)

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/nowdock-plasmoid#48]
Having the option to select dots and lines on top is nice (issue #45) when using nowdock panel so everything (i.e. nowdock plasmoid and other applets in the panel) look consistent.

However, in this case having the background on the other side does not make much sense (consider the case where the background is only a thin line that covers exactly that, the dots and lines; only that now lines and dots are moved to the other side).

I would like the option to be consistent also in that regard, so depending on where dots and lines appear, the background follows that selection.

I guess this would need to happen both in nowdock-plasmoid out of nowdock-panel and in nowdock-panel when used.

Does it make sense?

**Comment by kupiqu** [comment]
Alternatively, it would be good to have an option to overrride plasma's default in nowdock panel, so lines and dots always and consistently appear at bottom (if user prefers it).

Perhaps this option already exists but I couldn't find it.

**Comment by psifidotos** [comment]
The current behavior is in the plasmoid.. In the settings there is a new option for:
"Reverse position for lines and dots", this does not influence at all the background... The user can set the background to be bigger in that case in order to support lines and dots on top more consistently...

The now dock panel takes into account that choice only when the user has set it in the Now Dock plasmoid which is inside the panel...

does that make sense? did you manage to find it?

**Comment by kupiqu** [comment]
Yes, what I'm asking is in relation to the new feature you have just introduced.

Let me try to be clearer. One can now set top/bottom dots and lines in the plasmoid. Top has the advantage that fits well with plasma behavior, including other plasmoids present in nowdock-panel. 

However, no matter the selection, the background is only plot with bottom as a reference, so a user does not have the option to set narrow backgrounds and cover dots and lines if they appear at top.

What I am trying to advocate for is that the origin of the background should be coherent with the selected location of lines and dots. This would mean that if lines and dots appear at top, background should be plot from top to bottom, instead of from bottom to top...

Right now I use top lines and dots for consistency but I don't set any background because I like it to be quite narrow, just to cover lines and dots, and that is currently not possible for top selection, as they are plot from bottom.

I hope I was clearer this time :)

**Comment by psifidotos** [comment]
ok ok....

unfortunately I can not imagine it... How that case would look actually....
I believe that it wouldnt look ok, can you make a mockup?

Except that there is also the following:
- the background on top how it would behave with the zoom effect? because of the zoom effect there are dots and lines in different alignments

when I implemented this feature I had in my mind a panel background which reaches all to the top until the dots and lines and zoom factor:1, something like the default panel

![spectacle j31929](https://cloud.githubusercontent.com/assets/2216474/19223835/1155092e-8e82-11e6-82ae-c450a6b9c35f.png)

**Comment by kupiqu** [comment]
So true, I forgot about the zoom factor. Mmm, would it be a way to keep lines at bottom for other plasmoids in nowdock panel?

**Comment by kupiqu** [comment]
This is how it would look like for a left side panel (left is original with lines and dots at left side, right is mockup with lines and dots following plasma at right side).

![document-1-pagina001](https://cloud.githubusercontent.com/assets/3875196/19225152/f4ba404a-8e63-11e6-9a07-79ec6153639d.png)

I guess it only makes sense for zoom factor = 1

**Comment by psifidotos** [comment]
> would it be a way to keep lines at bottom for other plasmoids in nowdock panel?

unfortunately there isnt, to put the lines above the plasmoids is an internal plasma's design decision that can not be overcome...

> I guess it only makes sense for zoom factor = 1

I agree with you but I also dont think the complexity that will be added in the codepage worths it...

**Comment by kupiqu** [comment]
I agree

**Comment by psifidotos** [comment]
:+1:

**Comment by kupiqu** [comment]
Today I increased the width of the background when using the reversed location of lines and dots while keeping a zoom factor > 1, and I realized that:
1. either the width has to be asymmetrically big to account for the zoom
2. or  lines and dots appear out of the background during hovering (which I actually like)

Therefore I would like to reopen this issue with a slightly different perspective. Instead of changing the origin for the background, which I don't think would work fine, I would ask to add, in addition to the width, an offset, that by default would be 0 px, but could manually be changed if a user would like it.

I think this would not be so difficult to implement (but let me know if I'm wrong). This would allow to generate the behavior I'm looking for, so lines and dots appear as in plasma, and have a background around, then the zoom effect makes lines and dots to appear out of it, but that is actually a nice effect in my opinion.

Would you consider that possibility?

Thanks

**Comment by psifidotos** [comment]
do you mean that for the regular icon size it would look like your screenshot but when zoomed the panel background it will remain to its position? and that can be achieved with an offset?

**Comment by kupiqu** [comment]
Yes, during regular icon size it would look as in screenshot. When zoomed, icons would overlay but not surpass the background (not a big deal as background is behind). Only dots/lines would surpass and stay out of background when zoomed, but I think all together makes a nice effect (at least I would like to try it; in fact if you orient me a bit I can add the offset to the source code manually, test the effect and upload another screenshot).

I think this all can be achieved by adding a 'static' offset to the background (i.e. static in the sense that it does not dynamically change with zoom).

**Comment by psifidotos** [comment]
unfortunately this is not straight forward with the current implementation... the code is the PanelBox.qml for the NowDockPanel if you want to investigate... 

For the plasmoid is inside the main.qml and it is used from the taskslist  also, so I think that this can be achieved only with redesign of the code..

**Comment by kupiqu** [comment]
I see. I guess it's too much trouble then :)

**Comment by psifidotos** [comment]
let it be... we will see...

**Comment by psifidotos** [comment]
I will try to upload a branch in order for you to test this (it will break some of the default behavior but it will show if it worths it...

**Comment by psifidotos** [comment]
@kupiqu try **[line-above]** branch for now dock panel. And use **Bottom-Center** panel alignment and **icon-size:64** and **zoom-factor:1.5**

_my personal opinion is that it doesnt fit visually so well..._

**Comment by psifidotos** [comment]
![spectacle t15948](https://cloud.githubusercontent.com/assets/2216474/19410484/74882e18-92f6-11e6-8cf8-e9e40260c39f.png)

**Comment by kupiqu** [comment]
I do like it :)

I cannot see the branch, did you remove it?

**Comment by psifidotos** [comment]
no, it is in now dock panel...
https://github.com/psifidotos/nowdock-panel/tree/line-above

**Comment by kupiqu** [comment]
I tried it. Yes, I guess it's difficult to handle it given the combination of zooms, plus lines/dots, etc.
