### ISSUE TITLE
Icons turn greyscale when moved

### ISSUE THREAD

**Issue by lomapur** [psifidotos/nowdock-plasmoid#52]
Hello again!

When I move launchers around on the panel, the icons then stay greyscale and there is blue rectangle around them (see below). It seems that launching application fixes this issue (I mean, in this case launching Kodi fixes Kodi's icon and launching LO fixed LO's icon)

![screenshot_20161012_161012](https://cloud.githubusercontent.com/assets/3956272/19313423/aca29142-9096-11e6-8752-32ee9207e381.png)

**Comment by psifidotos** [comment]
which version of the plasmoid are u using?

**Comment by psifidotos** [comment]
I believe that no release event is triggered possibly...

**Comment by lomapur** [comment]
The newest released version (installed from the Store)

**Comment by psifidotos** [comment]
ok, I reproduced for version 0.3.2 but it is fixed in my system **[master]** branch, but master branch is compatible only with **Plasma 5.8**
