### ISSUE TITLE
line (for the window under focus) becomes a dot when previewing

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/nowdock-plasmoid#53]
The line (for the window under focus) becomes a dot when previewing either the same window or any other.

Note that I don't know if this is intended, neither whether or not it happens with the oficial plasma taskbars as well...

**Comment by psifidotos** [comment]
this could be a bug... this was not intended initially, do we prefer a different a behavior?

**Comment by kupiqu** [comment]
This is of minor importance, but I guess the line is to indicate the window under focus, so I would slightly prefer to keep the line, instead of to replace it by a dot, as the window under focus does not change by previewing (that same window or another).

**Comment by psifidotos** [comment]
the thing is that the "preview window" gets the active state... You can notice that from the color change in the title of the "active" window

**Comment by psifidotos** [comment]
but I believe I can handle the case and prepare the codebase

**Comment by kupiqu** [comment]
I see. That must be then the case in official plasma taskbars as well.
If you can easily handle it, that is great. Otherwise it's fine too. As said, this is a minor issue :)

**Comment by psifidotos** [comment]
I believe it is ok now...
