### ISSUE TITLE
Installation errors: no metadata file, old style JSON, deprecated code

### ISSUE THREAD

**Issue by alexhollinghead** [psifidotos/nowdock-plasmoid#57]
I'm running KDE Plasma 5.7.5 on Fedora 24. I'm having this problem with both versions 0.4 and 04. I execute "sh install-local.sh" and get this:
> No metadata file in the package, expected it at: "/home/alex/.local/share/"
> No metadata file in the package, expected it at: "/home/alex/.local/share/"
> Constructing a KPluginInfo object from old style JSON. Please use kcoreaddons_desktop_to_json() for "/home/alex/.local/share/plasma/plasmoids/nowdock-plasmoid/nowdockplasmoid" instead of kservice_desktop_to_json() in your CMake code.
> Constructing a KPluginInfo object from old style JSON. Please use kcoreaddons_desktop_to_json() for "/home/alex/.local/share/plasma/plasmoids/nowdock-plasmoid/nowdockplasmoid" instead of kservice_desktop_to_json() in your CMake code.
> No metadata file in the package, expected it at: "/home/alex/.local/share/plasma/plasmoids/"
> Calling KPluginInfo::property("X-KDE-PluginInfo-Name") is deprecated, use KPluginInfo::pluginName() in "/usr/lib64/qt5/plugins/plasma/packagestructure/plasma_packagestructure_share.so" instead.
> Calling KPluginInfo::property("X-KDE-PluginInfo-Name") is deprecated, use KPluginInfo::pluginName() in "/usr/lib64/qt5/plugins/plasma/packagestructure/plasma_packagestructure_share.so" instead.
> Successfully uninstalled /home/alex/.local/share/plasma/plasmoids/nowdock-plasmoid/nowdockplasmoid

After that, if I actually try to enable the plasmoid in a panel, it just collapses and gives me this error:
>Error loading QML file: file:///home/alex/.local/share/plasma/plasmoids/org.kde.store.nowdock.plasmoid/contents/ui/main.qml:243:9: Cannot assign to non-existent property "screenGeometry"

Any idea what's going on here?

**Comment by psifidotos** [comment]
> Any idea what's going on here?

Now Dock versions 0.4 are compatible only for Plasma 5.8 and beyond... You could use the 0.3 versions for Plasma 5.7

**Comment by alexhollinghead** [comment]
Thanks for the prompt repsonse. My original post contains a typo. I did try this with 0.3 and it failed also. Here's the error message when I try to use the 0.3 branch:

> No metadata file in the package, expected it at: "/home/alex/.local/share/"
> No metadata file in the package, expected it at: "/home/alex/.local/share/"
> Constructing a KPluginInfo object from old style JSON. Please use kcoreaddons_desktop_to_json() for "/home/alex/Downloads/nowdock-plasmoid/nowdockplasmoid" instead of kservice_desktop_to_json() in your CMake code.
> Constructing a KPluginInfo object from old style JSON. Please use kcoreaddons_desktop_to_json() for "/home/alex/Downloads/nowdock-plasmoid/nowdockplasmoid" instead of kservice_desktop_to_json() in your CMake code.
> No metadata file in the package, expected it at: "/home/alex/.local/share/plasma/plasmoids/"
> Calling KPluginInfo::property("X-KDE-PluginInfo-Name") is deprecated, use KPluginInfo::pluginName() in "/usr/lib64/qt5/plugins/plasma/packagestructure/plasma_packagestructure_share.so" instead.
> Calling KPluginInfo::property("X-KDE-PluginInfo-Name") is deprecated, use KPluginInfo::pluginName() in "/usr/lib64/qt5/plugins/plasma/packagestructure/plasma_packagestructure_share.so" instead.
> org.kde.plasma: Unable to remove  "/home/alex/.local/share/kservices5/plasma-applet-org.kde.store.nowdock.plasmoid.desktop"
> Error: Uninstallation of /home/alex/Downloads/nowdock-plasmoid/nowdockplasmoid failed: /home/alex/.local/share/plasma/plasmoids//org.kde.store.nowdock.plasmoid does not exist
> Generated  "/home/alex/.local/share/plasma/plasmoids//kpluginindex.json"  ( 2  plugins)
> Successfully installed /home/alex/Downloads/nowdock-plasmoid/nowdockplasmoid

**Comment by psifidotos** [comment]
> Error loading QML file: file:///home/alex/.local/share/plasma/plasmoids/org.kde.store.nowdock.plasmoid/contents/ui/main.qml:243:9: Cannot assign to non-existent property "screenGeometry"

The above line should occur only with 0.4 version, "screenGeometry" was introduced only in version 0.4. In the 0.3 branch opening the main.qml file the above variable does not exist. Are you sure you are using 0.3.2 nowdock plasmoid?

**Comment by alexhollinghead** [comment]
Turns out I hadn't fully removed the v0.4 that I installed mistakenly. Thanks for the help!

**Comment by psifidotos** [comment]
no worries... ;)
