### ISSUE TITLE
Window previews are sometimes shifted too far right, and get cropped.

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/nowdock-plasmoid#61]
In this demonstration video, it seems to be happening for all single windows, but not multi-windows.

Arch Linux
plasma-framework 5.28.0
plasma-desktop 5.8.4

https://streamable.com/42hw

**Comment by psifidotos** [comment]
@AndydeCleyre this must have been fixed in plasmoid's master with the latest commit...

**Comment by AndydeCleyre** [comment]
Yup, updated again and it looks good!

**Comment by psifidotos** [comment]
:+1:
